version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: timer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - my_network
    ports:
      - "8080:80"
    depends_on:
      - postgres

  api:
    build: .
    container_name: timer_api
    environment:
      DATABASE_URL: postgresql://root:root@postgres:5432/timer
      NODE_ENV: production
    networks:
      - my_network
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  import:
    build: .
    container_name: timer_import
    environment:
      DATABASE_URL: postgresql://root:root@postgres:5432/timer
      NODE_ENV: production
    volumes:
      - ./backup.json:/app/backup.json
    networks:
      - my_network
    depends_on:
      - postgres
    entrypoint: ["/import-entrypoint.sh"]
    profiles:
      - import

networks:
  my_network:
    driver: bridge

volumes:
  postgres-data:
