-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "color" TEXT NOT NULL DEFAULT '#000000',
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'EUR',
ADD COLUMN     "hourlyRate" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Timer" ADD COLUMN     "hourlyRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
